/**
 * Vocabulário visual do Librian — ícones semânticos (Lucide).
 * Preferir estes em vez de reutilizar BookOpen/Heart em tudo.
 */
export {
  LibraryBig as BrandIcon,
  Library as ShelfIcon,
  BookOpen as ReadingIcon,
  Book as UnreadIcon,
  Bookmark as WishlistIcon,
  BadgeCheck as ReadIcon,
  BookPlus as AddBookIcon,
  Mails as MagicLinkIcon,
  KeyRound as PasswordIcon,
  LogIn as LoginIcon,
  LogOut as LogoutIcon,
  Search as SearchIcon,
  Compass as ExploreIcon,
  SlidersHorizontal as FilterIcon,
  Star as RatingIcon,
  NotebookPen as NotesIcon,
  Building2 as PublisherIcon,
  CalendarDays as DateIcon,
  UserRound as ProfileIcon,
  Settings2 as SettingsIcon,
  Bell as NotificationsIcon,
  Menu as MenuIcon,
  X as CloseIcon,
  ChevronLeft,
  ChevronRight,
  ChevronRight as ChevronRightIcon,
  ArrowLeft,
  TrendingUp as ProgressIcon,
  LayoutGrid as GridIcon,
  List as ListIcon,
  ArrowUpDown as SortIcon,
  Upload as UploadIcon,
  Download as DownloadIcon,
  CheckCircle2 as SuccessIcon,
  AlertTriangle as WarningIcon,
  CircleAlert as ErrorIcon,
  Copy as DuplicateIcon,
  Trash2 as DeleteIcon,
  Pencil as EditIcon,
  Image as ImageIcon,
  Mail as MailIcon,
  Github as GithubIcon,
  Meh as AwkwardSmileIcon,
} from "lucide-react"
